package com.tsti.entidades;

/**
 * @author Bruno
 *
 */
public class Pasaje {

	/*
	 * PASAJE TIENE PRACTICAMENTE LOS MISMOS ATRIBUTOS QUE VUELO.
	 * NECESITAMOS REALMENTE UN PASAJE O LO IMPLEMENTAMOS SIMPLEMENTE
	 * COMO UN SERVICIO APARTE?
	 * */
	//ATRIBUTOS
	
	//CONSTRUCTOR
	
	//METODOS
}
